name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    - name: Setup Verilator
      run: sudo apt-get install verilator
    - name: Run tests
      run: sbt test
